#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXuatNhapHangHoa.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLXNHH")]
	public partial class QLXNHHDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHangHoa(HangHoa instance);
    partial void UpdateHangHoa(HangHoa instance);
    partial void DeleteHangHoa(HangHoa instance);
    partial void InsertPhieuXuat_ChiTiet(PhieuXuat_ChiTiet instance);
    partial void UpdatePhieuXuat_ChiTiet(PhieuXuat_ChiTiet instance);
    partial void DeletePhieuXuat_ChiTiet(PhieuXuat_ChiTiet instance);
    partial void InsertPhieuNhap(PhieuNhap instance);
    partial void UpdatePhieuNhap(PhieuNhap instance);
    partial void DeletePhieuNhap(PhieuNhap instance);
    partial void InsertPhieuNhap_ChiTiet(PhieuNhap_ChiTiet instance);
    partial void UpdatePhieuNhap_ChiTiet(PhieuNhap_ChiTiet instance);
    partial void DeletePhieuNhap_ChiTiet(PhieuNhap_ChiTiet instance);
    partial void InsertPhieuXuat(PhieuXuat instance);
    partial void UpdatePhieuXuat(PhieuXuat instance);
    partial void DeletePhieuXuat(PhieuXuat instance);
    #endregion
		
		public QLXNHHDatabaseDataContext() : 
				base(global::QLXuatNhapHangHoa.Properties.Settings.Default.QLXNHHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLXNHHDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLXNHHDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLXNHHDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLXNHHDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HangHoa> HangHoas
		{
			get
			{
				return this.GetTable<HangHoa>();
			}
		}
		
		public System.Data.Linq.Table<PhieuXuat_ChiTiet> PhieuXuat_ChiTiets
		{
			get
			{
				return this.GetTable<PhieuXuat_ChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<PhieuNhap> PhieuNhaps
		{
			get
			{
				return this.GetTable<PhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<PhieuNhap_ChiTiet> PhieuNhap_ChiTiets
		{
			get
			{
				return this.GetTable<PhieuNhap_ChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<PhieuXuat> PhieuXuats
		{
			get
			{
				return this.GetTable<PhieuXuat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangHoa")]
	public partial class HangHoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSHH;
		
		private string _TenHH;
		
		private System.Nullable<int> _TonDau;
		
		private EntitySet<PhieuXuat_ChiTiet> _PhieuXuat_ChiTiets;
		
		private EntitySet<PhieuNhap_ChiTiet> _PhieuNhap_ChiTiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSHHChanging(string value);
    partial void OnMSHHChanged();
    partial void OnTenHHChanging(string value);
    partial void OnTenHHChanged();
    partial void OnTonDauChanging(System.Nullable<int> value);
    partial void OnTonDauChanged();
    #endregion
		
		public HangHoa()
		{
			this._PhieuXuat_ChiTiets = new EntitySet<PhieuXuat_ChiTiet>(new Action<PhieuXuat_ChiTiet>(this.attach_PhieuXuat_ChiTiets), new Action<PhieuXuat_ChiTiet>(this.detach_PhieuXuat_ChiTiets));
			this._PhieuNhap_ChiTiets = new EntitySet<PhieuNhap_ChiTiet>(new Action<PhieuNhap_ChiTiet>(this.attach_PhieuNhap_ChiTiets), new Action<PhieuNhap_ChiTiet>(this.detach_PhieuNhap_ChiTiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSHH
		{
			get
			{
				return this._MSHH;
			}
			set
			{
				if ((this._MSHH != value))
				{
					this.OnMSHHChanging(value);
					this.SendPropertyChanging();
					this._MSHH = value;
					this.SendPropertyChanged("MSHH");
					this.OnMSHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHH
		{
			get
			{
				return this._TenHH;
			}
			set
			{
				if ((this._TenHH != value))
				{
					this.OnTenHHChanging(value);
					this.SendPropertyChanging();
					this._TenHH = value;
					this.SendPropertyChanged("TenHH");
					this.OnTenHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonDau", DbType="Int")]
		public System.Nullable<int> TonDau
		{
			get
			{
				return this._TonDau;
			}
			set
			{
				if ((this._TonDau != value))
				{
					this.OnTonDauChanging(value);
					this.SendPropertyChanging();
					this._TonDau = value;
					this.SendPropertyChanged("TonDau");
					this.OnTonDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_PhieuXuat_ChiTiet", Storage="_PhieuXuat_ChiTiets", ThisKey="MSHH", OtherKey="MSHH")]
		public EntitySet<PhieuXuat_ChiTiet> PhieuXuat_ChiTiets
		{
			get
			{
				return this._PhieuXuat_ChiTiets;
			}
			set
			{
				this._PhieuXuat_ChiTiets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_PhieuNhap_ChiTiet", Storage="_PhieuNhap_ChiTiets", ThisKey="MSHH", OtherKey="MSHH")]
		public EntitySet<PhieuNhap_ChiTiet> PhieuNhap_ChiTiets
		{
			get
			{
				return this._PhieuNhap_ChiTiets;
			}
			set
			{
				this._PhieuNhap_ChiTiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuXuat_ChiTiets(PhieuXuat_ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = this;
		}
		
		private void detach_PhieuXuat_ChiTiets(PhieuXuat_ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = null;
		}
		
		private void attach_PhieuNhap_ChiTiets(PhieuNhap_ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = this;
		}
		
		private void detach_PhieuNhap_ChiTiets(PhieuNhap_ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuXuat_ChiTiet")]
	public partial class PhieuXuat_ChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSPX;
		
		private string _MSHH;
		
		private int _SoLuong;
		
		private EntityRef<HangHoa> _HangHoa;
		
		private EntityRef<PhieuXuat> _PhieuXuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSPXChanging(string value);
    partial void OnMSPXChanged();
    partial void OnMSHHChanging(string value);
    partial void OnMSHHChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    #endregion
		
		public PhieuXuat_ChiTiet()
		{
			this._HangHoa = default(EntityRef<HangHoa>);
			this._PhieuXuat = default(EntityRef<PhieuXuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSPX", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSPX
		{
			get
			{
				return this._MSPX;
			}
			set
			{
				if ((this._MSPX != value))
				{
					if (this._PhieuXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSPXChanging(value);
					this.SendPropertyChanging();
					this._MSPX = value;
					this.SendPropertyChanged("MSPX");
					this.OnMSPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSHH
		{
			get
			{
				return this._MSHH;
			}
			set
			{
				if ((this._MSHH != value))
				{
					if (this._HangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSHHChanging(value);
					this.SendPropertyChanging();
					this._MSHH = value;
					this.SendPropertyChanged("MSHH");
					this.OnMSHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_PhieuXuat_ChiTiet", Storage="_HangHoa", ThisKey="MSHH", OtherKey="MSHH", IsForeignKey=true)]
		public HangHoa HangHoa
		{
			get
			{
				return this._HangHoa.Entity;
			}
			set
			{
				HangHoa previousValue = this._HangHoa.Entity;
				if (((previousValue != value) 
							|| (this._HangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangHoa.Entity = null;
						previousValue.PhieuXuat_ChiTiets.Remove(this);
					}
					this._HangHoa.Entity = value;
					if ((value != null))
					{
						value.PhieuXuat_ChiTiets.Add(this);
						this._MSHH = value.MSHH;
					}
					else
					{
						this._MSHH = default(string);
					}
					this.SendPropertyChanged("HangHoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuXuat_PhieuXuat_ChiTiet", Storage="_PhieuXuat", ThisKey="MSPX", OtherKey="MSPX", IsForeignKey=true)]
		public PhieuXuat PhieuXuat
		{
			get
			{
				return this._PhieuXuat.Entity;
			}
			set
			{
				PhieuXuat previousValue = this._PhieuXuat.Entity;
				if (((previousValue != value) 
							|| (this._PhieuXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuXuat.Entity = null;
						previousValue.PhieuXuat_ChiTiets.Remove(this);
					}
					this._PhieuXuat.Entity = value;
					if ((value != null))
					{
						value.PhieuXuat_ChiTiets.Add(this);
						this._MSPX = value.MSPX;
					}
					else
					{
						this._MSPX = default(string);
					}
					this.SendPropertyChanged("PhieuXuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuNhap")]
	public partial class PhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSPN;
		
		private System.DateTime _NgayNhap;
		
		private EntitySet<PhieuNhap_ChiTiet> _PhieuNhap_ChiTiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSPNChanging(string value);
    partial void OnMSPNChanged();
    partial void OnNgayNhapChanging(System.DateTime value);
    partial void OnNgayNhapChanged();
    #endregion
		
		public PhieuNhap()
		{
			this._PhieuNhap_ChiTiets = new EntitySet<PhieuNhap_ChiTiet>(new Action<PhieuNhap_ChiTiet>(this.attach_PhieuNhap_ChiTiets), new Action<PhieuNhap_ChiTiet>(this.detach_PhieuNhap_ChiTiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSPN", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSPN
		{
			get
			{
				return this._MSPN;
			}
			set
			{
				if ((this._MSPN != value))
				{
					this.OnMSPNChanging(value);
					this.SendPropertyChanging();
					this._MSPN = value;
					this.SendPropertyChanged("MSPN");
					this.OnMSPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date NOT NULL")]
		public System.DateTime NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_PhieuNhap_ChiTiet", Storage="_PhieuNhap_ChiTiets", ThisKey="MSPN", OtherKey="MSPN")]
		public EntitySet<PhieuNhap_ChiTiet> PhieuNhap_ChiTiets
		{
			get
			{
				return this._PhieuNhap_ChiTiets;
			}
			set
			{
				this._PhieuNhap_ChiTiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuNhap_ChiTiets(PhieuNhap_ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = this;
		}
		
		private void detach_PhieuNhap_ChiTiets(PhieuNhap_ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuNhap_ChiTiet")]
	public partial class PhieuNhap_ChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSPN;
		
		private string _MSHH;
		
		private int _SoLuong;
		
		private EntityRef<HangHoa> _HangHoa;
		
		private EntityRef<PhieuNhap> _PhieuNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSPNChanging(string value);
    partial void OnMSPNChanged();
    partial void OnMSHHChanging(string value);
    partial void OnMSHHChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    #endregion
		
		public PhieuNhap_ChiTiet()
		{
			this._HangHoa = default(EntityRef<HangHoa>);
			this._PhieuNhap = default(EntityRef<PhieuNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSPN", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSPN
		{
			get
			{
				return this._MSPN;
			}
			set
			{
				if ((this._MSPN != value))
				{
					if (this._PhieuNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSPNChanging(value);
					this.SendPropertyChanging();
					this._MSPN = value;
					this.SendPropertyChanged("MSPN");
					this.OnMSPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSHH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSHH
		{
			get
			{
				return this._MSHH;
			}
			set
			{
				if ((this._MSHH != value))
				{
					if (this._HangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSHHChanging(value);
					this.SendPropertyChanging();
					this._MSHH = value;
					this.SendPropertyChanged("MSHH");
					this.OnMSHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_PhieuNhap_ChiTiet", Storage="_HangHoa", ThisKey="MSHH", OtherKey="MSHH", IsForeignKey=true)]
		public HangHoa HangHoa
		{
			get
			{
				return this._HangHoa.Entity;
			}
			set
			{
				HangHoa previousValue = this._HangHoa.Entity;
				if (((previousValue != value) 
							|| (this._HangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangHoa.Entity = null;
						previousValue.PhieuNhap_ChiTiets.Remove(this);
					}
					this._HangHoa.Entity = value;
					if ((value != null))
					{
						value.PhieuNhap_ChiTiets.Add(this);
						this._MSHH = value.MSHH;
					}
					else
					{
						this._MSHH = default(string);
					}
					this.SendPropertyChanged("HangHoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_PhieuNhap_ChiTiet", Storage="_PhieuNhap", ThisKey="MSPN", OtherKey="MSPN", IsForeignKey=true)]
		public PhieuNhap PhieuNhap
		{
			get
			{
				return this._PhieuNhap.Entity;
			}
			set
			{
				PhieuNhap previousValue = this._PhieuNhap.Entity;
				if (((previousValue != value) 
							|| (this._PhieuNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuNhap.Entity = null;
						previousValue.PhieuNhap_ChiTiets.Remove(this);
					}
					this._PhieuNhap.Entity = value;
					if ((value != null))
					{
						value.PhieuNhap_ChiTiets.Add(this);
						this._MSPN = value.MSPN;
					}
					else
					{
						this._MSPN = default(string);
					}
					this.SendPropertyChanged("PhieuNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuXuat")]
	public partial class PhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSPX;
		
		private System.Nullable<System.DateTime> _NgayXuat;
		
		private EntitySet<PhieuXuat_ChiTiet> _PhieuXuat_ChiTiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSPXChanging(string value);
    partial void OnMSPXChanged();
    partial void OnNgayXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuatChanged();
    #endregion
		
		public PhieuXuat()
		{
			this._PhieuXuat_ChiTiets = new EntitySet<PhieuXuat_ChiTiet>(new Action<PhieuXuat_ChiTiet>(this.attach_PhieuXuat_ChiTiets), new Action<PhieuXuat_ChiTiet>(this.detach_PhieuXuat_ChiTiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSPX", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSPX
		{
			get
			{
				return this._MSPX;
			}
			set
			{
				if ((this._MSPX != value))
				{
					this.OnMSPXChanging(value);
					this.SendPropertyChanging();
					this._MSPX = value;
					this.SendPropertyChanged("MSPX");
					this.OnMSPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXuat
		{
			get
			{
				return this._NgayXuat;
			}
			set
			{
				if ((this._NgayXuat != value))
				{
					this.OnNgayXuatChanging(value);
					this.SendPropertyChanging();
					this._NgayXuat = value;
					this.SendPropertyChanged("NgayXuat");
					this.OnNgayXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuXuat_PhieuXuat_ChiTiet", Storage="_PhieuXuat_ChiTiets", ThisKey="MSPX", OtherKey="MSPX")]
		public EntitySet<PhieuXuat_ChiTiet> PhieuXuat_ChiTiets
		{
			get
			{
				return this._PhieuXuat_ChiTiets;
			}
			set
			{
				this._PhieuXuat_ChiTiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuXuat_ChiTiets(PhieuXuat_ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.PhieuXuat = this;
		}
		
		private void detach_PhieuXuat_ChiTiets(PhieuXuat_ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.PhieuXuat = null;
		}
	}
}
#pragma warning restore 1591
